AWSTemplateFormatVersion: "2010-09-09"
Description: Core Resources for Application (terraform-backend, ecr repositories)
Parameters:
    LIFECYCLE:
        Type: String
        Description: Lifecycle policy for repositories
        Default: "{\"rules\": [ { \"rulePriority\": 1, \"description\": \"Keep up to 10 images, expire the rest\", \"selection\": { \"tagStatus\": \"any\", \"countType\": \"imageCountMoreThan\", \"countNumber\": 10 }, \"action\": { \"type\": \"expire\" } } ]\r\n}"
Resources:
    WebRepo:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: con-pca-web
            LifecyclePolicy:
                LifecyclePolicyText: !Ref LIFECYCLE

    GophishRepo:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: con-pca-gophish
            LifecyclePolicy:
                LifecyclePolicyText: !Ref LIFECYCLE

    ApiRepo:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: con-pca-api
            LifecyclePolicy:
                LifecyclePolicyText: !Ref LIFECYCLE

    ReportsRepo:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: con-pca-reports
            LifecyclePolicy:
                LifecyclePolicyText: !Ref LIFECYCLE

    TerraformBackend:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: Private
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            BucketName: !Sub "con-pca-stage-tf-backend"

    SharedTerraformBackend:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: Private
            BucketEncryption:
                ServerSideEncryptionConfiguration:
                    - ServerSideEncryptionByDefault:
                        SSEAlgorithm: AES256
            BucketName: !Sub "con-pca-terraform"

    TerraformLock:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: con-pca-tf-lock
            BillingMode: PAY_PER_REQUEST
            
            KeySchema:
                - AttributeName: "LockID"
                  KeyType: HASH

            AttributeDefinitions:
                - AttributeName: "LockID"
                  AttributeType: "S"

