version: "3.5"

services:
  gophish:
    build:
      context: ./etc/gophish/
    container_name: pca-gophish
    hostname: gophish
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend
  nginx:
    build:
      context: ./etc/nginx/
    container_name: pca-gophish-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
  mysql:
    image: mysql:latest
    container_name: pca-gophish-db
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./etc/mysql/:/docker-entrypoint-initdb.d/
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
    env_file:
      - .env
  adminer:
    image: adminer
    container_name: pca-gophish-adminer
    restart: unless-stopped
    ports:
      - 9000:8080
    links:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    name: pca_backend
