version: '3.5'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: pca-localstack
    env_file:
      - .env
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    volumes:
      - pca-localstack-data:/tmp/localstack
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - backend
  terraform:
    build:
      context: .
      dockerfile: terraform.Dockerfile
    container_name: pca-terraform
    depends_on:
      - localstack
    image: cpa-terraform:1.0
    volumes:
      - pca-terraform-data:/app/state
      - './terraform:/app/resources'
    networks:
      - backend
volumes:
  pca-localstack-data:
  pca-terraform-data:

networks:
  backend:
    name: pca_backend
