name: COOL Deploy
on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [cool_stage]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.COOL_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.COOL_AWS_SECRET_ACCESS_KEY }}
  REGION: us-east-1

jobs:
  output:
    runs-on: ubuntu-latest
    # outputs:
    #   ENVIRONMENT: ${{ steps }}
    steps:
      - name: Set Environment
        id: env
        run: |
          echo ${{github.event_name}}
          echo ${{github.event.type}}
          echo ${{github.event.event_type}}
          echo ${{github.event.action}}
          echo ${{github.event.client_payload}}
        # if: ${{ github.event.client_payload.trigger ==  }}