name: COOL Deploy
on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [cool_staging, cool_production]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.COOL_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.COOL_AWS_SECRET_ACCESS_KEY }}
  REGION: us-east-1

jobs:
  setenv:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.env.outputs.ENVIRONMENT }}
    steps:
      - name: Echo Metadata
        run: |
          echo ${{ github.event.event_name }}
          echo ${{ github.event.action }}
      - name: Set Production on Dispatch
        run: $ENVIRONMENT=production
        if: ${{ github.event.action == cool_production}}
      - name: Set Staging on Push
        run: $ENVIRONMENT=staging
        if: ${{ github.event.event_name == push }}
      - name: Set Staging on Dispatch
        run: $ENVIRONMENT=staging
        if: ${{ github.event.action == cool_staging}}
      - name: Set Environment
        run: echo ::set-output name=ENVIRONMENT::$ENVIRONMENT
        id: env

  terraform:
    runs-on: ubuntu-latest
    needs: [setenv]
    env:
      ENVIRONMENT: ${{ needs.setenv.outputs.ENVIRONMENT }}
    steps:
      - name: Echo Environment
        run: echo $ENVIRONMENT
