name: COOL Deploy
on:
  push:
    branches: [develop]
  repository_dispatch:
    types: [cool_staging, cool_production]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.COOL_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.COOL_AWS_SECRET_ACCESS_KEY }}
  REGION: us-east-1

jobs:
  setenv:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.env.outputs.ENVIRONMENT }}
      AWS_PROVISION_ROLE: ${{ steps.env.outputs.AWS_PROVISION_ROLE }}

    steps:
      - uses: actions/checkout@v2
      - name: Echo Metadata
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}
      - name: Set Production
        working-directory: ./cool/
        run: cat ./vars/production.tfvars >> $GITHUB_ENV # echo "ENVIRONMENT=production" >> $GITHUB_ENV
        if: github.event.action == 'cool_production'
      - name: Set Staging
        working-directory: ./cool/
        run: cat ./vars/staging.tfvars >> $GITHUB_ENV #echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        if: github.event_name == 'push' || github.event.action == 'cool_staging'
      - name: Set Environment
        run: |
          echo ::set-output name=ENVIRONMENT::$env
          echo ::set-output name=AWS_PROVISION_ROLE::$github_actions_role
        id: env

  terraform:
    runs-on: ubuntu-latest
    needs: [setenv]
    env:
      ENVIRONMENT: ${{ needs.setenv.outputs.ENVIRONMENT }}
    steps:
      - name: Echo Environment
        run: echo $ENVIRONMENT
